### ISSUE TITLE
Part 4 of documentation does not include chaincode instantiation step

### ISSUE THREAD

**Issue by Gaurang10** [aws-samples/hyperledger-on-kubernetes#17]
The chaincode install step in included, however the instantiation step hasn't been included. The next steps described after installation assume that instantiation has been done. Might have been omitted in docs.

Also thanks a ton for the repo. Great work. Has been a truly helpful guide into fabric deployment

**Comment by MCLDG-zz** [comment]
Thanks for the kind words.

The chaincode was instantiated in part1. Instantiation only needs to be
done once on the channel.

**Comment by Gaurang10** [comment]
Aah got it. We were running the individual scripts to get a deeper understanding and running into problems. 

Been trying to help my company automate and streamline HL Fabric deployment and your repo has truly helped us get an understanding of how to integrate the CA into the mix. We were relying the Cello repo till now. 

It's still an uphill climb though, this fabric keeps breaking randomly. Do you have any tips/guides aside from the official docs?

**Comment by MCLDG-zz** [comment]
I'd use Amazon managed blockchain. Managing the infra for a fabric network
isn't for the faint of heart. 😁
